apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
<<<<<<< HEAD
        image: evertz2022/devops:replaceImageTag
=======
        image: abhishekf5/ultimate-cicd:13
>>>>>>> dacf73687ac0c1033e1d95362b51f938e1a79740
        ports:
        - containerPort: 8080
